[versions]
# --- Core ---
agp = "8.11.2"
coreKtxVersion = "1.5.0"
espressoCore = "3.5.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "2.0.21"
coreKtx = "1.17.0"

# --- Compose ---
composeUi = "1.9.4"
composeTooling = "1.7.5"
composeMaterial3 = "1.3.0"
activityCompose = "1.9.3"
mockitoCore = "5.13.0"
mockitoInline = "5.2.0"
mockitoKotlin = "5.3.1"
mockkAndroid = "1.13.12"
navigationCompose = "2.8.3"

# --- Lifecycle ---
lifecycle = "2.8.3"

# --- Coroutines ---
coroutines = "1.8.1"

# --- Hilt ---
hilt = "2.47"
hiltNavigationCompose = "1.1.0-alpha01"

# --- Networking ---
retrofit = "2.11.0"
converterGson = "2.11.0"
okhttp = "5.0.0-alpha.14"

# --- Coil (Image Loading) ---
coilCompose = "2.6.0"

# --- UI Support ---
appcompat = "1.7.1"
material = "1.13.0"
rules = "1.5.0"
turbine = "1.2.1"
turbineVersion = "1.1.0"
uiTestJunit4 = "1.7.4"
uiTestManifest = "1.7.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
# --- Android Core ---
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# --- Compose ---
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeTooling" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeTooling" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# --- Lifecycle ---
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# --- Coroutines ---
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# --- Hilt ---
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# -- Image Loading ---
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# --- Networking ---
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# --- UI Support ---
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbineVersion" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }